FROM php:7.3-fpm-alpine

LABEL maintainer="ariopra@gmail.com"

RUN apk upgrade --update && apk add --no-cache --virtual .build-deps  \
        alpine-sdk \
        autoconf \
        automake \
        cmake \
        g++ \
        libtool \
    && apk add --no-cache \
        libwebp-dev \
        libjpeg-turbo-dev \
        libjpeg-turbo-utils \
        freetype-dev \
        libmcrypt-dev \
        libpng-dev \
        libxpm-dev \
        icu-dev \
        bzip2-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        imagemagick \
        imagemagick-dev \
        graphviz \
        ttf-dejavu \
        ttf-droid \
        ttf-freefont \
        ttf-liberation \
        ttf-ubuntu-font-family \
    && apk add --no-cache \
        bash \
        shadow \
    && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-xpm-dir=/usr/include \
        --with-webp-dir=/usr/include/ \
    && docker-php-ext-install intl mysqli bcmath gd bz2 soap xmlrpc xsl pdo_mysql exif zip opcache iconv \
    \
    && pecl config-set php_ini  /usr/local/etc/php/php.ini \
    \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick \
    \
    && pecl install apcu \
    && pecl install redis \
    && pecl install xdebug \
    && docker-php-ext-enable redis apcu xdebug \
    \
    && apk add gnu-libiconv --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
    \
    && cd ~ \
    \
    && git clone https://github.com/google/zopfli.git \
        && cd zopfli \
        && make \
        && cp zopfli /usr/bin/zopflipng \
        && cd .. \
        && rm -rf zopfli \
    \
    && wget https://github.com/imagemin/pngout-bin/raw/master/vendor/linux/x64/pngout -O /bin/pngout \
        && chmod 0755 /bin/pngout \
    \
    && wget http://prdownloads.sourceforge.net/advancemame/advancecomp-1.17.tar.gz \
        && tar zxvf advancecomp-1.17.tar.gz \
        && cd advancecomp-1.17 \
        && ./configure \
        && make \
        && make install \
        && cd .. \
        && rm -rf advancecomp-1.17 \
    && apk del .build-deps \
        && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \

COPY .docker/app/usr/local/etc/php/conf.d/*.ini /usr/local/etc/php/conf.d/

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

COPY --from=aantonw/alpine-wkhtmltopdf-patched-qt /bin/wkhtmltopdf /usr/bin/wkhtmltopdf
COPY --from=aantonw/alpine-wkhtmltopdf-patched-qt /bin/wkhtmltoimage /usr/bin/wkhtmltoimage

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_MEMORY_LIMIT -1
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN set -eux; \
    composer clear-cache
ENV PATH="${PATH}:/root/.composer/vendor/bin"

RUN usermod -u 1000 www-data \
    && groupmod -g 1000 www-data

